Repository Ingressive-for-Good/I4G-OPENSOURCE-BACKEND-PROJECT-2022, pull requests merged in 2022-10, with the labels that each got.

#18 Code of conduct
  CONTRIBUTING.md
  code_of_conduct.md
  images/I4G-OPENSOURCE-IMAGE.jpg
  issue_template.md
Labels: documentation, enhancement, hacktoberfest-accepted

#14 updated contributing file
  CONTRIBUTING.md
  images/I4G-OPENSOURCE-IMAGE.jpg
Labels: documentation, enhancement, hacktoberfest-accepted

#25 Product Model
  src/models/categories.model.ts
  src/models/products.model.ts
  src/models/user.model.ts
  src/modules/user/user.model.ts
Labels: hacktoberfest-accepted

#32 adding eslint and prettier configuration
  .eslintrc.json
  .prettierrc.json
  CONTRIBUTING.md
  README.md
  code_of_conduct.md
  issue_template.md
  package-lock.json
  package.json
  src/app.js
  src/helper/logger.js
  src/index.js
  src/utils/config.js
  src/utils/error.js
  src/utils/helpers.js
Labels: help wanted, hacktoberfest-accepted, backend

#38 User model
  src/models/category.model.js
  src/models/product.model.js
  src/modules/user.model.js
Labels: hacktoberfest-accepted, backend

#40 Fix the condition object in the product model
  src/models/product.model.js
Labels: hacktoberfest-accepted

#46 user authentication
  .env
  package-lock.json
  package.json
  src/app.js
  src/helper/connect.js
  src/index.js
  src/middlewares/input.validator.js
  src/modules/user.controller.js
  src/modules/user.model.js
  src/modules/user.routes.js
  src/modules/user.service,js
  src/modules/user.service.js
  src/modules/user.validator.js
  src/utils/config.js
  src/utils/error.js
  src/utils/helpers.js
  src/views/auth.ejs
Labels: hacktoberfest-accepted, backend

#45 User profile
  README.md
  src/app.js
  src/models/category.model.js
  src/models/product.model.js
  src/modules/profile.controller.js
  src/modules/profile.route.js
Labels: hacktoberfest-accepted, backend

#44 User product
  src/app.js
  src/modules/product.controller.js
  src/modules/product.routes.js
  src/modules/user.controller.js
Labels: hacktoberfest-accepted

#57 Add the product module
  package-lock.json
  package.json
  src/app.js
  src/common/middlewares/body.validation.middleware.js
  src/middlewares/multer-errorHandler.js
  src/models/chats.model.js
  src/models/posts.model.js
  src/models/product.model.js
  src/modules/category/category.controller.js
  src/modules/category/category.model.js
  src/modules/category/category.route.js
  src/modules/category/category.service.js
  src/modules/category/category.validator.js
  src/modules/product.controller.js
  src/modules/product.routes.js
  src/modules/product/product.controller.js
  src/modules/product/product.model.js
  src/modules/product/product.route.js
  src/modules/product/product.service.js
  src/modules/profile/profile.controller.js
  src/modules/profile/profile.route.js
  src/modules/user/user.route.js
  src/routes/category.route.js
  src/utils/cloudinary.js
  src/utils/helpers.js
  src/utils/multer.js
Labels: hacktoberfest-accepted, backend

#60 Add the delete a product by user feature
  src/modules/product/product.controller.js
  src/modules/product/product.route.js
  src/modules/product/product.service.js
Labels: hacktoberfest-accepted, backend

#61 [hacktoberfest:] feat: Implement get products enpoint
  src/modules/product/product.controller.js
  src/modules/product/product.route.js
  src/modules/product/product.service.js
Labels: hacktoberfest-accepted, backend

#63 Update single product endpoint
  src/modules/product/product.controller.js
  src/modules/product/product.route.js
  src/modules/product/product.service.js
Labels: hacktoberfest-accepted, backend

#65 User message
  package-lock.json
  package.json
  src/app.js
  src/index.js
  src/modules/chat/chat.controller.js
  src/modules/chat/chat.model.js
  src/modules/chat/chat.route.js
  src/modules/chat/chat.service.js
  src/modules/message/message.controller.js
  src/modules/message/message.model.js
  src/modules/message/message.route.js
  src/modules/message/message.service.js
  src/modules/product/product.controller.js
  src/socket.js
Labels: hacktoberfest-accepted, backend
